### ISSUE TITLE
Move to bs4_book?

### ISSUE THREAD

**Issue by Bisaloo** [colrverse/colsci-book#4]
The development version of bookdown offers a newer version for a HTML book: bs_book.

The nice part is that it includes [downlit](https://github.com/r-lib/downlit), and functions are  now auto-magically link to their pkgdown documentation (which was already the case in the old pkgdown website).

However, I don't like the newer look as much...

![image](https://user-images.githubusercontent.com/10783929/107936838-6c1a6480-6f83-11eb-939b-e2d097769c07.png)

**Comment by thomased** [comment]
Hmm, the linking would be nice. And I don't actually mind the look tbh. Title fonts are clean (I like the abbreviation of `Chapter 2 Importing...` to `2 Importing...`), sidebar heading is properly wrapped & the search is in a more useful/discoverable spot. 

Would have to play to see how the split-navigation feels but in principle I'm on board if you're up for it.

**Comment by Bisaloo** [comment]
You can see for example the 'R packages' book if you want to test more: https://r-pkgs.org/index.html

**Comment by thomased** [comment]
Ah nice. Yeah I actually prefer it, if I had to pick one.
